config/routes.rb
Rails.application.routes.draw do
  
  get 'password_reset/new'
  get 'password_reset/edit'

  root 'home#index'
  
  resources :users do
    member do
      get :delete
    end 
    member do
      get :resend_activation
    end
    member do
      get :crop_avatar
    end
  end
  
  resources :private_messages, except: [:edit, :update] do 
    member do
      get :delete
    end
    member do
      get :unread
    end
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_reset, only: [:new, :create, :edit, :update]
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get    '/logout', to: 'sessions#destroy'

end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  
  layout 'basic'
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  include SessionsHelper
  
  def new
  end
  
  def create 
    @user = User.find_by_email(params[:password_reset][:email].downcase)
    unless @user
      flash.now[:warning] = 'That email address does not exist.'
      render('new')      
    else
      @user.create_reset_digest
      flash[:notice] = "Check your email for password reset instructions."
      UserMailer.password_reset(@user).deliver_now
      redirect_to(root_url)
    end
  end
  
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "cannot be empty.")
      render('edit')
    elsif @user.update_attributes(user_params)
      log_in(@user)
      flash[:notice] = "Password has been reset."
      redirect_to(@user)
    else
      render('edit')
    end
  end

  def edit
  end
  
private

  def get_user
    @user = User.find_by_email(params[:email])
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def valid_user
    unless(@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
      flash[:warning] = "Something went horribly wrong.  Just wrong."
      redirect_to(root_url)
    end
  end
  
  def check_expiration
    if @user.password_reset_expired?
      flash[:warning] = "Password reset has expired."
      redirect_to(new_password_reset_url)
    end
  end
  
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_reset/edit.html.erb
<div class="basic-form">
  <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
    <%= hidden_field_tag(:email, @user.email) %>
    <div class="finput clearfix">
      <div class="flabel"><%= f.label(:password) %></div>
      <%= f.password_field(:password) %>
    </div>
    <div class="finput clearfix">
      <div class="flabel"><%= f.label('Confirm Password') %></div>
      <%= f.password_field(:password_confirmation) %>
    </div>
    <div class="fsubmit clearfix">
      <%= f.submit("Update Password") %>
    </div>
  <% end %>
</div>

app/views/password_reset/new.html.erb
<div class="basic-form">
  <%= form_for(:password_reset, url: password_reset_index_path) do |f| %>
  <div class="finput clearfix">
    <div class="flabel"><%= f.label(:email) %></div>
    <%= f.email_field(:email) %>
  </div>
  <div class="fsubmit clearfix">
    <%= f.submit("Submit") %>
  </div>
  <% end %>
</div>
  
  
  
  
  