config/routes.rb
Rails.application.routes.draw do
  
  get 'password_reset/new'
  get 'password_reset/edit'

  root 'home#index'
  
  resources :users do
    member do
      get :delete
    end 
    member do
      get :resend_activation
    end
    member do
      get :crop_avatar
    end
  end
  
  resources :private_messages, except: [:edit, :update] do 
    member do
      get :delete
    end
    member do
      get :unread
    end
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_reset, only: [:new, :create, :edit, :update]
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get    '/logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password
    has_attached_file :avatar, :styles => { :tiny => "30x30#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "avatar/:style.jpg"
    has_many :private_messages, :dependent => :destroy
    crop_attached_file :avatar
    before_save :downcase_email
    before_create :create_activation_digest

    attr_accessor :remember_token, :activation_token, :reset_token
    
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    USER_REGEX = /\A^[a-zA-Z0-9_\- ]*$\z/
    
    validates :name,  presence: true, 
                      length: { within: 6..50 },
                      uniqueness: { case_sensitive: false },
                      format: { with: USER_REGEX, :message => 'can only be letters, numbers, dash, space, and underscore' }
                      
    validates :email, presence: true, 
                      length: { maximum: 255 },
                      format: { with: EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    
    validates :password, presence: true,
                         length: { :within => 6..50 },
                         :if => :password
                         
    validates :password_confirmation, presence: true,
                                      :if => :password
                                      
    validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"], :message => 'must be jpg, jpeg, png, or gif',
                                               :if => :avatar
                                               
    validates_attachment_size :avatar, :less_than => 3.megabytes,
                                       :if => :avatar
                                       
    # CHANGES EMAILS ADDRESS TO LOWERCASE
    def downcase_email
      self.email = email.downcase
    end
    
    # CREATES TOKEN AND DIGEST FOR PASSWORD RESET PROCEDURE -
    def create_reset_digest
      self.reset_token = User.new_token
      update_attribute(:reset_digest, User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
    end
    
    # CHECKS TO SEE IF PASSWORD RESET IS EXPIRED
    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end
    
    # CREATES TOKEN AND DIGEST FOR ACTIVATION PROCEDURE
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    
    # RESETS THE ACTIVATION TOKEN AND DIGEST SO USER CAN TRY AGAIN
    def reset_activation_digest
      self.create_activation_digest
      self.update_attribute(:activation_digest, self.activation_digest)
    end
    
    # ENCRYPTS STRING                                  
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    
    # GENERATES TOKENS                                  
    def User.new_token
      SecureRandom.urlsafe_base64  
    end
    
    # SETS REMEMBER DIGEST IN DB TO REMEMBER USER WHEN THEY RETURN
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # CHECKS REMEMBER TOKEN AGAINST DB
    def authenticated?(attribute, token)
      digest = send("#{attribute}_digest")
      return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
    end
    
    # FORGETS USER SO THEY'LL HAVE TO LOG IN AGAIN
    def forget
      update_attribute(:remember_digest, nil)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout 'basic'
  include ApplicationHelper
  include SessionsHelper
  before_action :has_permission, :only => [:edit, :update, :delete, :destroy, :crop_avatar]
  before_action :remember_location, :only => [:index, :show]
  
    
  def index
    if logged_in?
      @users = User.where(:activated => true).order("name ASC").paginate(page: params[:page], :per_page => 6)
    else
      flash[:warning] = "<li>You must be logged in to see that page.</li>"
      redirect_to(root_url)
    end
  end
  
  def show
    unless @user = User.find_by_id(params[:id])
      flash[:warning] = "<li>That user does not exist.</li>"
      redirect_to(root_path)
    end
    unless @user.activated?
      flash[:warning] = "<li>That user is not activated.</li>"
      redirect_to(users_url(page: params[:page]))
    end    
  end
  
  def new
    @user = User.new
    @heading = "Register here"
    @form_submit = "Submit registration"
  end  
    
  def create
    @user = User.new(user_params)
    @user.role = 'common'
    
    unless @user.save
      compile_errors(@user, "now", "warning")
      render('new') and return false
    end
    
    UserMailer.account_activation(@user).deliver_now
    flash[:notice] = "Please check your email to activate your account."
    redirect_to(root_url)
  end
  
  def resend_activation
    @user = User.find(params[:id])
    unless @user.activated      
      @user.reset_activation_digest
      UserMailer.account_activation(@user).deliver_now
      flash[:notice] = "Your activation email has been sent again. Please check your junk folder if you cannot find it."
      redirect_to(root_url)  
    else
      flash[:warning] = "That account has already been activated."
      redirect_to(root_url)      
    end
  end
  
  def edit
    unless @user = User.find(params[:id])
      flash[:warning] = "<li>That user does not exist.</li>"
      redirect_to(root_path)
    end
    @heading = "Edit your data"
    @form_submit = "Save your changes"
  end
  
  def crop_avatar
    unless @user = User.find(params[:id])
      flash[:warning] = "<li>That user does not exist.</li>"
      redirect_to(root_path)
    end
    if @user.avatar_file_name.blank?
      flash[:warning] = "<li>That user does not have an avatar.</li>"
      redirect_to(@user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if params[:user][:password].blank?
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end
    
    unless @user.update_attributes(user_params)
      compile_errors(@user, "now")
      render('edit') and return false
    end
    
    flash[:notice] = "#{@user.name} has been updated successfully."
    redirect_to(@user)
  end
  
  def delete
    @user = User.find(params[:id])
  end
  
  def destroy
    user = User.find(params[:id])
    log_out unless is_admin?
    user.destroy
    private_messages_to_destroy = PrivateMessage.where(sender_id: params[:id])
    private_messages_to_destroy.each do |pm|
      pm.destroy
    end
    flash[:notice] = "User '#{user.name}' has been destroyed."
    redirect_to(root_url)
  end
  
  
  private
  
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :email, :biography, :avatar, :avatar_original_w, :avatar_original_h, :avatar_crop_x, :avatar_crop_y, :avatar_crop_w, :avatar_crop_h)
    end 
    
    def has_permission
      unless is_self?(params[:id].to_i) || is_admin?
        flash[:warning] = "<li>You do not have permission to #{params[:action]} that.</li>"
        redirect_to(root_url)
      end
    end  
  

end

app/helpers/users_helper.rb
module UsersHelper
    
end

app/views/users/_new-edit-form.html.erb
<h1><%= @heading %></h1>

<div class="basic-form">
  <%= form_for(@user, html: { multipart: true }) do |f| %>
    <div class="finput clearfix">
      <div class="flabel"><%= f.label("Desired user name") %></div>
      <%= f.text_field(:name) %>
    </div>
    <div class="finput clearfix">
      <div class="flabel"><%= f.label("Password") %></div>
      <%= f.password_field(:password) %>
    </div>
    <div class="finput clearfix">
      <div class="flabel"><%= f.label("Confirm password") %></div>
      <%= f.password_field(:password_confirmation) %>
    </div>
    <div class="finput clearfix">
      <div class="flabel"><%= f.label("Your email") %></div>
      <%= f.text_field(:email) %>
    </div>
    <div class="ffile clearfix">
      <div class="flabel"><%= f.label("Your Image") %></div>
      <%= f.file_field(:avatar) %>
    </div>  
    <div class="finput clearfix" id="user-bio">
      <div class="flabel"><%= f.label("Biography") %></div>
      <%= f.text_area(:biography, :rows => 8) %>
    </div>  
    <div class="fsubmit clearfix">
      <%= f.submit(@form_submit, :id => "new-edit-submit") %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="user-listing clearfix">
  <%= image_tag(user.avatar.url(:thumb), style: 'float:left; margin:0 12px 0 0; width: 100px; height: 100px') %>

  <span class="name">
    <%= link_to(user.name, user_path(user)) %>
    <%= "*" if user.role == 'admin' %>
  </span>  

  <div class="action-link"><%= link_to("[edit]", edit_user_url(user)) if is_self?(user.id) || is_admin? %></div>
  <div class="action-link"><%= link_to("[delete me]", delete_user_url(user)) if is_self?(user.id) || is_admin? %></div>

  <div class="biography">
    <%= truncate(user.biography, :length => 125) %>
  </div>  
</div>

app/views/users/crop_avatar.html.erb
<h1>Original Image</h1>
<div class="basic-form">
  <%= form_for(@user, html: { multipart: true }) do |f| %>
    <div class="fcrop clearfix">
      <div class="image">
        <%= f.cropbox :avatar, :width => 300 %>
      </div>
    </div>
    <h1>Crop Preview</h1>
    <%= f.crop_preview :avatar %>
    <div class="fsubmit clearfix">
      <%= f.submit 'Save' %>
    </div>
  <% end %>
</div>

app/views/users/delete.html.erb
<div class="basic-form">
  <%= form_for(@user, :method => 'delete') do |f| %>
    Are you sure that you want to delete <%= @user.name %>?<br>
    This cannot be undone.<br><br>
    <div class="fsubmit">
      <%= f.submit("Yes, Delete me") %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render(:partial => 'new-edit-form') %>

<script>
  $(document).on('turbolinks:load', function() {
    $("#new-edit-submit").val("Save Changes");
  });
</script>

app/views/users/index.html.erb
<div class="text-content-wrapper">
  <h1>User Directory</h1>
  <%= render @users %>
  <div class="pagination_info">
    <%= page_entries_info @users, :model => 'message' %>
  </div>
  <div class="pagination">
    <%= will_paginate(:container => false, :previous_label => '<< Back', :next_label => 'Forward >>') %>
  </div>
</div>

app/views/users/new.html.erb
<%= render(:partial => 'new-edit-form') %>

<script>
  $(document).on('turbolinks:load', function() {
    $("#user-bio").hide();
  });
</script>

app/views/users/show.html.erb
<div class="user-page clearfix">
  <div class="text-content-wrapper">
    <h1><%= @user.name %></h1>
    <div class="profile-wrapper">
      <div class="user-image clearfix">
          <% if is_self?(@user.id) || is_admin? %>
              <div class="dropdown-edit">
                <button class="dropbtn-edit">Editing Options</button>
                <div class="dropdown-edit-content">
                  <%= link_to("[Crop Image]", crop_avatar_user_url(@user), :"data-turbolinks" => false) %>
                  <%= link_to("[Edit Profile]", edit_user_url(@user), :"data-turbolinks" => false) %>
                </div>
              </div><br>       
          <% end %>       
        <%= image_tag(@user.avatar.url(:medium)) %>
        <div class="user-contact">
          <%= link_to("Send Private Message", new_private_message_url("private_message[user_id]" => @user.id)) %>
        </div>
      </div>
    <%= simple_format(@user.biography) %>
    </div>
  </div>
</div>