config/routes.rb
Rails.application.routes.draw do
  
  get 'password_reset/new'
  get 'password_reset/edit'

  root 'home#index'
  
  resources :users do
    member do
      get :delete
    end 
    member do
      get :resend_activation
    end
    member do
      get :crop_avatar
    end
  end
  
  resources :private_messages, except: [:edit, :update] do 
    member do
      get :delete
    end
    member do
      get :unread
    end
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_reset, only: [:new, :create, :edit, :update]
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get    '/logout', to: 'sessions#destroy'

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    
    attr_accessor :recipient_id
    belongs_to :user
    validates :subject, presence: true
    validates :message, presence: true
    
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  
  include ApplicationHelper
  include SessionsHelper
  require 'will_paginate/array' 
  before_action :need_to_login?
  before_action :remember_location, :only => [:index]
  layout 'basic'
  
  def index
    @private_messages_raw = PrivateMessage.where("user_id = ?", session[:user_id]).order('created_at DESC')
    @private_messages_new = Array.new
    @private_messages_old = Array.new
    @private_messages_raw.each do |pm|
      pm.read_date? ? @private_messages_old << pm : @private_messages_new << pm
    end
    @private_messages = @private_messages_new + @private_messages_old 
    @private_messages = @private_messages.paginate(:per_page => 5, :page => params[:page])
  end
  
  def show
    @private_message = PrivateMessage.find(params[:id])
    unless @private_message.user_id == session[:user_id]
      flash[:warning] = "That is someone else's message!"
      redirect_to(private_messages_url) and return false
    end
    @private_message.update_attribute(:read_date, Time.zone.now)
  end
  
  def new
    unless params[:private_message][:user_id].present?
      flash[:warning] = "<li>You cannot send a message with no recipient.</li>"
      redirect_to(session[:location]) and return false
    end
    @private_message = PrivateMessage.new
    @private_message.user_id = params[:private_message][:user_id]
    @private_message.reply_id = params[:private_message][:reply_id]
    unless user_id_valid?(@private_message.user_id)
      flash[:warning] = "<li>You cannot send a message to a user that does not exist.</li>"
      redirect_to(session[:location])
    end
    @private_message = load_original_message_text(@private_message) unless @private_message.reply_id.nil?
  end
 
  def create
    @private_message = PrivateMessage.new(message_params)
    @private_message.sender_id = session[:user_id]
    unless @private_message.save
      compile_errors(@private_message, "now", "warning")
      render('new') and return false
    end
    @recipient = User.find(params[:private_message][:user_id])
    UserMailer.private_message(@recipient, @private_message).deliver_now
    flash[:notice] = "<li>Your message has been sent to #{User.find(@private_message.user_id).name}.</li>"
    redirect_to(session[:location])
  end
  
  def unread
    unless @private_message = PrivateMessage.find(params[:id])
      flash[:warning] = "<li>That message does not exist.</li>"
      redirect_to(session[:location]) and return false
    end
    @private_message.update_attribute(:read_date, nil)
    redirect_to(session[:location])
  end
  
  def delete
    @private_message = PrivateMessage.find(params[:id])
  end
  
  def destroy
    private_message = PrivateMessage.find(params[:id])
    private_message.destroy
    flash[:notice] = "A message has been destroyed."
    redirect_to(session[:location])
  end  
  
  
  private
  
    def message_params
      params.require(:private_message).permit(:subject, :message, :user_id, :reply_id)
    end 
    
    def need_to_login?
      unless logged_in?
        flash[:warning] = '<li>You must be logged in for private message features to work.</li>'
        redirect_to(login_url) and return false
      end
    end

    def user_id_valid?(user_id)
      return true unless User.find_by_id(user_id).nil?
    end
    
    def load_original_message_text(private_message)
      reply_text = PrivateMessage.find_by_id(private_message.reply_id)
      unless reply_text.nil?
        private_message.message = reply_text.message.prepend("\n\n==== REPLYING TO ====\n")
        private_message.subject = reply_text.subject.prepend("RE: ").gsub(/(RE: )+/, 'RE: ')
      end
      return private_message
    end
    
end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
end

app/views/private_messages/_private_message.html.erb
<div class="message-listing clearfix">
  <div class="image">
    <%= image_tag(User.find(private_message.sender_id).avatar.url(:thumb)) %>  
  </div>  
  <div class="subject <%= "unread" if private_message.read_date.blank? %>">
    <%= link_to("[NEW]", private_message_url(private_message)) if private_message.read_date.blank? %> 
    <%= link_to(private_message.subject.truncate(60, separator: /\s/), private_message_url(private_message)) %>   
  </div>
  <div class="sent-date">From <%= User.find(private_message.sender_id).name %> - <%= time_ago_in_words(private_message.created_at) %> ago</div>
  <div class="intro">
    <%= private_message.message.truncate(150, separator: /\s/) %>  
  </div>    
</div>

app/views/private_messages/delete.html.erb
<div class="basic-form">
  <%= form_for(@private_message, :method => 'delete') do |f| %>
    Are you sure that you want to delete <%= @private_message.subject %>?<br>
    This cannot be undone.<br><br>
    <div class="fsubmit">
      <%= f.submit("Yes, Delete the message") %>
    </div>
  <% end %>
</div>

app/views/private_messages/index.html.erb
<div class="text-content-wrapper">
  <h1>Private messages</h1>
  <% if @private_messages.blank? %>
    You do not have any messages.
  <% end %>
  <%= render @private_messages %>
  
  <div class="pagination_info">
    <%= page_entries_info @private_messages, :model => 'message' %>
  </div>
  <div class="pagination">
    <%= will_paginate(:container => false, :previous_label => '<< Back', :next_label => 'Forward >>') %>
  </div>
</div>

app/views/private_messages/new.html.erb
<h1>Send a message to <%= User.find(@private_message.user_id).name %></h1>

<div class="basic-form">
  <%= form_for(@private_message) do |f| %>
    <%= f.hidden_field(:user_id, :value => @private_message.user_id) %>
    <div class="finput clearfix">
      <div class="flabel"><%= f.label(:subject) %></div> 
      <%= f.text_field(:subject) %>
    </div>
    <div class="finput clearfix" id="user-bio">
      <div class="flabel"><%= f.label(:message) %></div>
      <%= f.text_area(:message, :rows => 8) %>
    </div>  
    <div class="fsubmit clearfix">
      <%= f.submit("Send Message") %>
    </div>    
  <% end %>  
</div>

app/views/private_messages/show.html.erb
<div class="text-content-wrapper">
  <div class="private-message clearfix">
    <div class="avatar">
      <%= link_to(image_tag(User.find(@private_message.sender_id).avatar.url(:thumb)), image_url(User.find(@private_message.sender_id).avatar.url(:medium)), target: '_blank')%>
    </div>
    <div class="subject">
       <%= @private_message.subject %>
    </div>  
    <div class="sender">
      From <%= User.find(@private_message.sender_id).name %>  
    </div>
    <div class="message">
      <%= simple_format(@private_message.message) %>  
    </div>
    <%= link_to("Delete this message", delete_private_message_path(@private_message)) %>&nbsp;|&nbsp;
    <%= link_to("Mark as unread", unread_private_message_url(@private_message)) %>&nbsp;|&nbsp;
    <%= link_to("Reply", new_private_message_url("private_message[user_id]" => @private_message.sender_id, "private_message[reply_id]" => @private_message.id)) %>
  </div>
</div>