config/routes.rb
Rails.application.routes.draw do
  
  get 'password_reset/new'
  get 'password_reset/edit'

  root 'home#index'
  
  resources :users do
    member do
      get :delete
    end 
    member do
      get :resend_activation
    end
    member do
      get :crop_avatar
    end
  end
  
  resources :private_messages, except: [:edit, :update] do 
    member do
      get :delete
    end
    member do
      get :unread
    end
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_reset, only: [:new, :create, :edit, :update]
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get    '/logout', to: 'sessions#destroy'

end

app/views/layouts/_logged-in-user.html.erb
<div class="user-nav">
  <% new_mail = @current_user.private_messages.where(read_date: nil).count %>
  <div class="dropdown">
    <button class="dropbtn"><%= link_to(image_tag("new-mail.png"), private_messages_url) if new_mail > 0 %><%= @current_user.name %></button>
    <div class="dropdown-content">
      <%= link_to(new_mail.to_s + " unread messages", private_messages_url) %>
      <%= link_to("Profile", user_url(@current_user)) %>
      <%= link_to("All Users", users_url) %>
      <%= link_to("Log Out", logout_path) %>
    </div>
    <%= image_tag @current_user.avatar.url(:tiny) %>
  </div> 
  <div class="screen-top-navigation"><%= render(:partial =>'layouts/navigation') %></div>
</div>  

app/views/layouts/_logged-out-user.html.erb
<div class="user-nav clearfix">
  <div class="dropdown">
    <button class="dropbtn">Hey Stranger!</button>
    <div class="dropdown-content">
      <%= link_to("Register", new_user_path) unless request.path == new_user_path %>
      <%= link_to("Log In", login_path) unless request.path == login_path %>
    </div>
    <%= image_tag("avatar/tiny.jpg") %>
  </div> 
  <div class="screen-top-navigation"><%= render(:partial =>'layouts/navigation') %></div>
</div>  

app/views/layouts/_navigation.html.erb
<div class="menu-collapsed" id="menu-expander">  
  <%= image_tag('menu-collapsed.png') %>
</div>
<ul>
  <li <%= 'class="current"'.html_safe if request.path == "/" %>><%= link_to("Home", root_url) %></li>
  <li><a href="#">About</a></li>
  <li><a href="#">Contact</a></li>
  <li><a href="#">Whatever</a></li>
</ul>

app/views/layouts/basic.html.erb
<!DOCTYPE html>
<head>
  <title></title>
  <meta name="viewport" content="width=device-width">
  <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Patua+One" rel="stylesheet"> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="user-menu clearfix">  
  <%= logged_in? ? render(:partial =>'layouts/logged-in-user') : render(:partial => 'layouts/logged-out-user') %>
</div> 

<% if request.path == "/" %>
  <div class="hero">
    <div class="text">
      <h1>Stonewall On Rails</h1>
    </div>
  </div>
<% end %>  

<% unless flash[:warning].nil? %>
  <div class="flash-warning">
    <ul><%= flash[:warning].html_safe %></ul>
  </div>
<% end %>
  
<% unless flash[:notice].nil? %>
  <div class="flash-notice">
    <ul><%= flash[:notice].html_safe %></ul>
  </div>
<% end %>  
  
<div class="page-wrapper">
  <%= yield %>
</div>  

</body>
</html>